---
id: foxnews

stages:
- process: node index.js
  subscribe: index
  publish: category
  pipe: each

- process: node category.js
  subscribe: category
  publish: article
  pipe: each

- process: node article.js
  subscribe: article
  publish: elastic
