---
id: foxnews

stages:
- process: node $CRAWLER_ROOT/src/foxnews/index.js
  subscribe: index
  publish: category
  pipe: each

- process: node $CRAWLER_ROOT/src/foxnews/category.js
  subscribe: category
  publish: article
  pipe: each

- process: node $CRAWLER_ROOT/src/foxnews/article.js
  subscribe: article
  publish: elastic
